const {chromium}=require('playwright'), assert=require('assert'), fs=require('fs'), crypto=require('crypto');
const cfg=JSON.parse(fs.readFileSync(process.argv[2])), wait=ms=>new Promise(r=>setTimeout(r,ms));
async function ctl(action,prompt='none',who='alice',id) {const r=await fetch(cfg.control,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,prompt,who,id})});const j=await r.json();assert(r.ok,JSON.stringify(j));return j.value;}
async function until(fn,label,seconds=15) {const end=Date.now()+seconds*1000;while(Date.now()<end){const r=await fn();if(r)return r;await wait(30);}throw new Error('timeout: '+label);}
const original=async(id,token=cfg.alice)=>{const r=await fetch(cfg.base+'/api/turns/'+id,{headers:{Authorization:'Bearer '+token}});const v=await r.json();assert.strictEqual(r.status,200,JSON.stringify(v));return v;};
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.JIACLAW_TEST_CHROMIUM?{executablePath:process.env.JIACLAW_TEST_CHROMIUM}:{})});console.log('BROWSER VERSION '+browser.version());
 const page=await browser.newPage({viewport:{width:1360,height:1000}}), errors=[], requests=[], puts=[];
 page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{const path=new URL(r.url()).pathname;requests.push({path,method:r.method(),auth:r.headers().authorization});if(r.method()==='PUT')puts.push({path,body:r.postDataJSON(),auth:r.headers().authorization});});
 const connect=async(token=cfg.alice)=>{await page.locator('#api-token').fill(token);await page.locator('#connect-form button').click();await page.waitForFunction(()=>!document.getElementById('turn-workspace').hidden&&!document.getElementById('status').textContent.startsWith('连接中'),null,{timeout:10000}).catch(async()=>{throw new Error('actual tenant workbench refused connection: '+await page.locator('#status').textContent());});};
 const begin=async prompt=>{await page.locator('#new-session').click();await page.locator('#turn-permissions summary').click();assert.strictEqual(await page.locator('#turn-permissions input:checked').count(),0);await page.locator('#turn-tools input[value="datetime_now"]').check();await page.locator('#message').fill(prompt);await page.locator('#send').click();await page.waitForFunction(()=>document.getElementById('turn-id').value.length===36);return page.locator('#turn-id').inputValue();};
 const finish=async()=>{await page.waitForFunction(()=>!document.getElementById('turn-finish').disabled);await page.locator('#turn-finish').click();};
 const lookup=async id=>{await page.locator('#turn-lookup-id').fill(id);await page.locator('#turn-lookup button').click();await page.waitForFunction(()=>!document.getElementById('turn-check').disabled);};
 const terminal=async id=>until(async()=>{const v=await original(id);return v.receipt.state!=='running'&&!v.active?v:null;},'actual original terminal');
 const noStorage=async()=>assert.strictEqual(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
 try {
  await page.goto(cfg.base);await connect();assert.strictEqual(await page.locator('#new-session').isDisabled(),false);assert.strictEqual(await page.locator('#turn-catalog-filter').isVisible(),false);assert((await page.locator('#turn-mode').textContent()).includes('30 秒'));
  await page.locator('#new-session').click();await page.locator('#message').fill('permission-negative');await page.locator('#send').click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('请选择本次允许'));
  assert.strictEqual(puts.length,0);assert.strictEqual((await ctl('status','permission-negative')).count,0);assert.strictEqual(await page.locator('#turn-tools input').count(),2);assert.strictEqual(await page.locator('#turn-skills input').count(),0);await connect();
  const prompt='<img src=x onerror="window.TENANT_XSS=1">原回复🦀';const first=await begin(prompt);await finish();let actual=await original(first);
  assert.strictEqual(actual.receipt.result.reply,'alice: '+prompt);assert((await page.locator('#messages').textContent()).includes('alice: '+prompt));assert.strictEqual(await page.locator('#messages img').count(),0);assert.strictEqual(await page.evaluate(()=>typeof window.TENANT_XSS),'undefined');assert.strictEqual(await page.locator('#message').inputValue(),'');
  assert.strictEqual(puts.length,1);assert.strictEqual(puts[0].path,'/api/turns/'+first);assert.deepStrictEqual(puts[0].body.enabled_tools,['datetime_now']);assert.deepStrictEqual(puts[0].body.enabled_skills,[]);assert.strictEqual(puts[0].auth,'Bearer '+cfg.alice);assert.strictEqual((await ctl('status',prompt)).count,1);await noStorage();
  console.log('PASS tenant browser 1: actual personal-key JSON connect/submit/finite observation, explicit fixed tools and text-only original committed reply');

  await ctl('gate','browser-reload');const reloadId=await begin('browser-reload');await until(async()=>{const s=await ctl('status','browser-reload');return s.ready&&s.count===1},'actual gated model');const beforeReload=puts.length;
  await page.reload();assert.strictEqual(await page.locator('#api-token').inputValue(),'');await noStorage();await connect(cfg.readonly);assert.strictEqual(await page.locator('#turn-id').inputValue(),reloadId);assert((await page.locator('#turn-state').textContent()).includes('处理中'));
  assert.strictEqual(await page.locator('#turn-cancel').isDisabled(),true);assert.strictEqual(await page.locator('#send').isDisabled(),true);assert.strictEqual(await page.locator('#turn-retry').isDisabled(),true);assert.strictEqual(puts.length,beforeReload);
  await ctl('release','browser-reload');await terminal(reloadId);await page.locator('#turn-check').click();await finish();assert((await page.locator('#messages').textContent()).includes('alice: browser-reload'));assert.strictEqual((await ctl('status','browser-reload')).count,1);
  await connect(cfg.bob);assert.strictEqual(await page.locator('#messages .message').count(),0);assert.strictEqual(await page.locator('#turn-id').inputValue(),'');await lookup(reloadId);await page.waitForFunction(()=>document.getElementById('status').textContent.includes('unavailable'));assert.strictEqual(await page.locator('#turn-finish').isDisabled(),true);assert.strictEqual(await page.locator('#turn-cancel').isDisabled(),true);assert.strictEqual(puts.length,beforeReload);await connect();
  console.log('PASS tenant browser 2: reload retains only original fragment, readonly GET recovery while JSON execution continues, changed identity/cross-user lookup cannot reveal or replay');

  // Create actual additional permanent admissions for finite user-only pagination.
  const extra=[];
  for(let i=0;i<5;i++){await until(async()=>!(await ctl('status')).holds.length,'settled user hold');const id=crypto.randomUUID(),body={session_id:'http:'+crypto.randomUUID(),prompt:'catalog-'+i,enabled_tools:['datetime_now']};const r=await fetch(cfg.base+'/api/turns/'+id,{method:'PUT',headers:{Authorization:'Bearer '+cfg.alice,'Content-Type':'application/json'},body:JSON.stringify(body)});assert.strictEqual(r.status,202,await r.text());extra.push(id);await terminal(id);}
  await page.goto(cfg.base);await connect(cfg.readonly);await page.locator('#turn-catalog summary').click();await page.locator('#turn-catalog-refresh').click();await page.waitForFunction(()=>document.getElementById('turn-catalog-rows').childElementCount===5);
  assert((await page.locator('#turn-catalog-rows').textContent()).includes('执行状态须另行核对'));assert.strictEqual(await page.locator('#turn-id').inputValue(),'');const firstPage=await page.locator('#turn-catalog-rows button').evaluateAll(nodes=>nodes.map(n=>n.dataset.turnId));await page.locator('#turn-catalog-next').click();await page.waitForFunction(()=>document.getElementById('turn-catalog-status').textContent.startsWith('第 6'));
  const secondPage=await page.locator('#turn-catalog-rows button').evaluateAll(nodes=>nodes.map(n=>n.dataset.turnId));assert(secondPage.every(id=>!firstPage.includes(id)));assert(secondPage.includes(first));const catalogPuts=puts.length;await page.locator(`[data-turn-id="${first}"]`).click();await finish();assert((await page.locator('#messages').textContent()).includes(prompt));assert.strictEqual(puts.length,catalogPuts);await noStorage();
  await page.route('**/api/turns?**',async route=>{const r=await route.fetch({maxRetries:0,maxRedirects:0});const j=await r.json();j.requests[0].state='completed';await route.fulfill({response:r,json:j});});await page.locator('#turn-catalog-refresh').click();await page.waitForFunction(()=>document.getElementById('turn-catalog-status').textContent.includes('未通过核对'));assert.strictEqual(await page.locator('#turn-catalog-rows button').count(),0);assert.strictEqual(await page.locator('#turn-catalog-next').isDisabled(),true);await page.unroute('**/api/turns?**');await connect(cfg.bob);await page.locator('#turn-catalog summary').click();await page.locator('#turn-catalog-refresh').click();await page.waitForFunction(()=>document.getElementById('turn-catalog-status').textContent.startsWith('本页暂无'));await connect();
  console.log('PASS tenant browser 3: lost fragment discovers exact own metadata then original GET, finite distinct pages, readonly catalog, no fabricated execution state or malformed rows');

  await ctl('gate','browser-cancel');const cancelled=await begin('browser-cancel');await until(async()=>{const s=await ctl('status','browser-cancel');return s.ready&&s.count===1},'cancel gate');await page.waitForFunction(()=>!document.getElementById('turn-cancel').disabled);await page.locator('#turn-cancel').click();await until(async()=>(await original(cancelled)).receipt.cancel_requested,'durable cancel');await ctl('release','browser-cancel');actual=await terminal(cancelled);assert.strictEqual(actual.receipt.state,'needs_review');await page.locator('#turn-check').click();await page.waitForFunction(()=>!document.getElementById('turn-gateway-review').hidden);
  assert.strictEqual(await page.locator('#turn-review').isVisible(),false);assert.strictEqual(await page.locator('#turn-abandon').isDisabled(),true);assert.strictEqual(await page.locator('#turn-finish').isDisabled(),true);
  // The backend receipt can settle before the gateway's independent observer
  // persists its retained review hold. Check that actual transition explicitly.
  const cancelledHold=await until(async()=>{const s=await ctl('status','browser-cancel');return s.holds.length===1&&s.holds[0].state==='needs_review'?s:null;},'gateway cancel hold settlement');assert.strictEqual(cancelledHold.holds[0].request_id,cancelled);assert.strictEqual(cancelledHold.count,1);
  await ctl('review','none','alice',cancelled);await page.locator('#turn-check').click();await finish();
  console.log('PASS tenant browser 4: original persisted cancellation retains actual settlement/user review, personal UI has no review/purge authority, independent idle admin reconciliation');

  await ctl('gate','browser-loss');let lostBody;await page.route('**/api/turns/*',async route=>{if(route.request().method()!=='PUT')return route.continue();lostBody=route.request().postDataJSON();await route.fetch({maxRetries:0,maxRedirects:0});await route.abort('failed');});const lost=await begin('browser-loss');await until(async()=>{const s=await ctl('status','browser-loss');return s.ready&&s.count===1},'lost actual dispatch');await page.waitForFunction(()=>!document.getElementById('turn-retry').disabled);assert.strictEqual(await page.locator('#message').inputValue(),'browser-loss');await page.unroute('**/api/turns/*');page.once('dialog',d=>d.accept());await page.locator('#turn-retry').click();await page.waitForFunction(()=>document.getElementById('turn-state').textContent.includes('处理中'));assert.strictEqual(puts.at(-1).path,'/api/turns/'+lost);assert.deepStrictEqual(puts.at(-1).body,lostBody);assert.strictEqual((await ctl('status','browser-loss')).count,1);await ctl('release','browser-loss');await finish();assert.strictEqual((await ctl('status','browser-loss')).count,1);
  console.log('PASS tenant browser 5: actual PUT response loss preserves draft/UUID, explicit identical retry uses gateway lookup-only identity and never repeats model dispatch');

  await ctl('gate','browser-restart');const restarted=await begin('browser-restart');await until(async()=>(await ctl('status','browser-restart')).ready,'restart gate');await ctl('restart');await ctl('release','browser-restart');await terminal(restarted);await page.reload();await connect();await page.waitForFunction(()=>document.getElementById('turn-id').value.length===36);await finish();assert.strictEqual((await ctl('status','browser-restart')).count,1);assert.strictEqual((await ctl('status','browser-restart')).holds[0].state,'needs_review');
  // Ending view tracking does not silently clear the gateway's restart review.
  const blocked=await begin('blocked-after-restart');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('review')||document.getElementById('status').textContent.includes('progress'));assert.strictEqual((await ctl('status','blocked-after-restart')).count,0);assert.strictEqual(await page.locator('#turn-id').inputValue(),blocked);await connect();
  console.log('PASS tenant browser 6: real gateway SIGKILL/restart, original GET recovery without model replay, ending UI tracking never releases registry review/capacity');

  // Other user's actual reply remains usable after Alice's unreconciled restart hold.
  await connect(cfg.bob);const bob=await begin('bob-original');await finish();assert((await page.locator('#messages').textContent()).includes('bob: bob-original'));assert.strictEqual((await ctl('status','bob-original','bob')).count,1);assert.strictEqual(await page.evaluate(()=>location.hash),'');
  await page.route('**/api/turns/capabilities',async route=>{const r=await route.fetch({maxRetries:0,maxRedirects:0});const j=await r.json();j.streaming=true;await route.fulfill({response:r,json:j});});await page.locator('#api-token').fill(cfg.bob);await page.locator('#connect-form button').click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('协议'));assert.strictEqual(await page.locator('#new-session').isDisabled(),true);assert.strictEqual(await page.locator('#turn-workspace').isVisible(),false);await page.unroute('**/api/turns/capabilities');await connect(cfg.bob);
  // A present gateway's denied/unavailable tracked capability grants no legacy
  // sending authority. Only an explicit missing feature may use legacy routes.
  for(const denied of [403,503]){
   const legacyReads=requests.filter(r=>r.path==='/api/sessions').length, priorPuts=puts.length;
   await page.route('**/api/turns/capabilities',route=>route.fulfill({status:denied,contentType:'application/json',body:JSON.stringify({error:'fixture tracked capabilities unavailable'})}));
   await page.locator('#api-token').fill(cfg.bob);await page.locator('#connect-form button').click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('fixture tracked capabilities unavailable'));
   assert.strictEqual(await page.locator('#new-session').isDisabled(),true);assert.strictEqual(await page.locator('#turn-workspace').isVisible(),false);assert.strictEqual(requests.filter(r=>r.path==='/api/sessions').length,legacyReads);assert.strictEqual(puts.length,priorPuts);await page.unroute('**/api/turns/capabilities');
  }
  await connect(cfg.bob);
  await ctl('gate','browser-stale','bob');const stale=await begin('browser-stale');await until(async()=>(await ctl('status','browser-stale','bob')).ready,'old identity actual owner');await connect(cfg.readonly);await ctl('release','browser-stale','bob');await until(async()=>{const v=await original(stale,cfg.bob);return v.receipt.state!=='running'&&!v.active},'old identity settlement');
  assert.strictEqual(await page.locator('#turn-id').inputValue(),'');assert.strictEqual(await page.locator('#messages .message').count(),0);assert.strictEqual(await page.locator('#message').inputValue(),'');assert.strictEqual((await ctl('status','browser-stale','bob')).count,1);await noStorage();
  console.log('PASS tenant browser 8: identity replacement during an actual JSON execution hides late results/credentials, detached original owner completes once');

  await connect(cfg.bob);await until(async()=>!(await ctl('status','browser-stale','bob')).holds.length,'gateway old identity hold settlement');
  // Deliberately fault the initial PUT response as well as every GET. A valid
  // fast execution may already be completed in its PUT response, so GET-only
  // injection does not reliably exercise a running observation window.
  let observationGets=0, observationPuts=0;await page.route('**/api/turns/*',async route=>{const method=route.request().method();if(!['PUT','GET'].includes(method))return route.continue();const r=await route.fetch({maxRetries:0,maxRedirects:0});const j=await r.json();assert.strictEqual(r.status(),method==='PUT'?202:200,JSON.stringify(j));if(method==='GET')observationGets++;else observationPuts++;j.active=true;j.receipt={...j.receipt,state:'running',finished_ms:null,session_committed:false,result:null,result_purged:false,error:null,reviewed_ms:null,review_note:null};await route.fulfill({response:r,json:j});});
  const observedStart=Date.now(), observed=await begin('browser-observation-deadline');await page.waitForFunction(()=>document.getElementById('status').textContent.includes('本页观察已结束'),null,{timeout:40000}).catch(async error=>{throw new Error(error.message+' '+JSON.stringify({elapsed:Date.now()-observedStart,status:await page.locator('#status').textContent(),turn:await page.locator('#turn-state').textContent(),observationGets,observationPuts,actual:await ctl('status','browser-observation-deadline','bob')}));});assert(Date.now()-observedStart>=29500&&Date.now()-observedStart<35000);assert.strictEqual(observationPuts,1);assert(observationGets>1);assert.strictEqual(await page.locator('#turn-finish').isDisabled(),true);assert.strictEqual(await page.locator('#send').isDisabled(),true);assert.strictEqual((await ctl('status','browser-observation-deadline','bob')).count,1);const observedPuts=puts.length;await page.unroute('**/api/turns/*');await page.locator('#turn-check').click();await finish();assert.strictEqual(puts.length,observedPuts);
  console.log('PASS tenant browser 9: deliberately faulty running DTO never resets actual 30-second browser window or proves completion; original GET reconciles one committed execution');
  await page.setViewportSize({width:380,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await noStorage();assert(requests.every(r=>!r.path.endsWith('/stream')&&!r.path.endsWith('/review')&&!r.path.endsWith('/result')));assert(requests.every(r=>!r.path.startsWith('/api/tools')&&!r.path.startsWith('/api/skills')));assert(requests.every(r=>!r.path.startsWith('/api/sessions/http')));assert(requests.filter(r=>r.auth).every(r=>[cfg.alice,cfg.bob,cfg.readonly].includes(r.auth.slice(7))));assert.deepStrictEqual(errors,[]);
  console.log('PASS tenant browser 7: independent user remains usable, malformed mode refuses connection without fallback, no private token/history/review/stream probes, mobile/text/storage bounds');
  await ctl('stop-backend','none','bob');await page.goto(cfg.base);await connect(cfg.bob);assert.strictEqual(await page.locator('#session-list-state').isVisible(),true);await page.locator('#turn-catalog summary').click();await page.locator('#turn-catalog-refresh').click();await page.locator(`[data-turn-id="${observed}"]`).waitFor();const offlinePuts=puts.length;await page.locator(`[data-turn-id="${observed}"]`).click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('review required'));assert.strictEqual(await page.locator('#turn-id').inputValue(),observed);assert.strictEqual(await page.locator('#turn-finish').isDisabled(),true);assert.strictEqual(await page.locator('#messages .message').count(),0);assert.strictEqual(puts.length,offlinePuts);
  console.log('PASS tenant browser 10: actual private backend shutdown leaves authenticated registry catalog accessible; missing original receipt stays unknown without fabricated reply or replay');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
